### ISSUE TITLE
MCS enabled modules endpoint

### ISSUE THREAD

**Issue by Alevsk** [minio/mcs#115]
We need the ability of adding or removing elements from the Menu on MCS based on how minio is configured, ie: ldap, kes, oidc, prometheus, etcd, etc are enabled

<img width="274" alt="Screen Shot 2020-05-11 at 11 59 57 PM" src="https://user-images.githubusercontent.com/1795553/81648480-a0089e00-93e3-11ea-95b4-0b3bf1a70eaf.png">

Currently we have the the config endpoint but we cannot rely 100% on it since I noticed that if LDAP its enabled or the region is changed via environment variables the returned configuration doesn't contain that information, however MinIO its running with those configuration, we need to discuss if this is a bug on MinIO or its the intended behavior and we need to make MCS aware about those configuration ie:

```
export LDAP_ENABLED=on
export KES_ENABLED=on
export OIDC_ENABLED=on
export ETCD_ENABLED=on
...
./mcs server
```

**Comment by dvaldivia** [comment]
I think we can infer all of these from the other existing configurations, we can infect OpenID and LDAP, for kes we can read the configuration from MinIO
