### ISSUE TITLE
Viewing a policy and exiting its modal results in deletion

### ISSUE THREAD

**Issue by labebe6** [minio/mcs#172]
@dvaldivia so sorry, but because of this bug, I've accidentally deleted a few IAM policies on the account you shared with the design team. https://play.min.io:9443/. Just want to check that if this is happening across instances and if it can be fixed. Just clicking the close button on the top right, deletes the policy from the list.

<img width="1065" alt="Screen Shot 2020-06-15 at 1 47 54 PM" src="https://user-images.githubusercontent.com/57810560/84704602-f3a06700-af0e-11ea-94d9-197532127d8c.png">

**Comment by cesnietor** [comment]
Oh ok I was able to reproduce it, it is not actually deleting it but it does disappears from the list, if we click refresh it appears again. This might be just UI issue. 
Thanks @labebe6

**Comment by labebe6** [comment]
Cool. Just wanted to make sure. Thanks @cesnietor

**Comment by cesnietor** [comment]
Note: it seems that the list of policies from minIO is not returned in any order, so after any refresh the list changes.

**Comment by bexsoft** [comment]
Will take a look on that
