### ISSUE TITLE
Support for Safari

### ISSUE THREAD

**Issue by jaredkipe** [minio/mcs#184]
In Safari, Login page works for getting errors when credentials are wrong, but when you provide correct credentials the page reloads and you do not get any visible errors anywhere.

the 'token' cookie does get set, and it does have the correct domain/content.
there is no local storage created

FF has both after login.

**Comment by dvaldivia** [comment]
nice catch @jaredkipe I see the behavior, strangely enough, on local it doesn't happen, only when deployed, we'll investigate.

**Comment by dvaldivia** [comment]
I see that the cookie is getting attached on localhost but not when deployed online, however we are actually passing the `Bearer` authorization header, so it shouldn't matter, maybe the missing cookie has something to do with privacy setting in Safari


On Local
<img width="822" alt="Screen Shot 2020-06-29 at 10 05 40 AM" src="https://user-images.githubusercontent.com/18384552/86034898-46d6e700-b9f0-11ea-9433-a1fc27c89ebf.png">

Deployed (play)
<img width="748" alt="Screen Shot 2020-06-29 at 10 05 47 AM" src="https://user-images.githubusercontent.com/18384552/86034925-55bd9980-b9f0-11ea-9046-5e1f7fe6ffd6.png">
