### ISSUE TITLE
[Question] Resetting secrets

### ISSUE THREAD

**Issue by phucduong86** [minio/mcs#198]
Hi,

I initialized my container with the following secrets and accidentally deleted the workspace with it.
Now when i spin up the container using a different secret (cannot remember/locate the old one) I get 401 Unauthorized response when I try to login.

MCS_HMAC_JWT_SECRET
MCS_PBKDF_PASSPHRASE
MCS_PBKDF_SALT
Is it possible to reset these secrets from my minio server?

Thank you

![image](https://user-images.githubusercontent.com/21692768/88104774-ecedbb00-cb70-11ea-9cf6-33a5d35158a2.png)

**Comment by dvaldivia** [comment]
@Alevsk if the JWT phrases change, it means only previous sessions won't work right?

**Comment by Alevsk** [comment]
> @Alevsk if the JWT phrases change, it means only previous sessions won't work right?

Yes, previous JWT will be invalid and the user will need to login again.

@phucduong86 please share the logs of mcs console, we will see more information there.

**Comment by phucduong86** [comment]
@Alevsk  @dvaldivia 
I created the credentials and it seems to work now. Seems that Minio server takes a while to apply the latest changes from my commands even though it sent successful result.
Thank you for the quick responses.
