### ISSUE TITLE
Dialog component that matches design

### ISSUE THREAD

**Issue by dvaldivia** [minio/mcs#56]
We need a dialog component that matches the design on xd

<img width="785" alt="Screen Shot 2020-04-09 at 9 24 08 AM" src="https://user-images.githubusercontent.com/18384552/78917756-2e37e000-7a44-11ea-8d10-3d1aaef77791.png">

**Comment by bexsoft** [comment]
Implemented ModalWrapper Component, will replace all the modals in mcs & close this issue

**Comment by bexsoft** [comment]
#66 Ready for Review

**Comment by bexsoft** [comment]
#66 merged
