### ISSUE TITLE
UI | creating a postgres notification event returns error if sslmode is enabled

### ISSUE THREAD

**Issue by cesnietor** [minio/mcs#76]
When creating a postgres notification event it returns that `enable` is not supported.
```
code":500,"message":"pq: unsupported sslmode \"enable\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"}

```

**Comment by dvaldivia** [comment]
Looks like the set of possible values for `sslmode` is a wide range of options, I'll change that field to a select

<img width="743" alt="Screen Shot 2020-04-21 at 11 45 40 AM" src="https://user-images.githubusercontent.com/18384552/79902049-ab107580-83c5-11ea-8dc1-2b180e49991f.png">
